### PR TITLE
contrib: add sway-session.target

### PR DESCRIPTION
**Pull request by markstos**
See:  https://github.com/swaywm/sway/pull/5622

### CODE REVIEW

**Review by OctopusET — CHANGES_REQUESTED** [review]
Could you add original authors as co-author?

**Comment by markstos** [comment]
@maximbaz opened the linked PR against Sway, but did not author the lines, they were were copied from the Sway wiki. I'm not sure who added it there. 

Another version exists in the sway-services repo: https://github.com/xdbob/sway-services/blob/master/systemd/sway-session.target that was written by @xdbob

Almost identical code appears in the sway-systemd project, where it it was written by @alebastr

https://github.com/alebastr/sway-systemd/blob/main/units/sway-session.target

For all these folks, I don't have email addresses to include in the usual Git `Co-Authored-By:` convention. 

It's pretty generic, simple piece of code that appeared in several places by several people before it landed it here. You welcome to amend the commit to add as mention of the above people in whatever you way you like.

**Comment by max-baz** [comment]
Speaking for my part, you have my full permission and support to merge this without mentioning my name in the commit message 😊👍

**Comment by xdbob** [comment]
> Another version exists in the sway-services repo: https://github.com/xdbob/sway-services/blob/master/systemd/sway-session.target that was written by @xdbob

[...]

> For all these folks, I don't have email addresses to include in the usual Git `Co-Authored-By:` convention.

I don't think my unit is worth a `Co-Authored-By:` in any case, if you wish, you can tag me as `Antoine Damhet <xdbob@xdbob.net>`  otherwise,

Acked-by: Antoine Damhet \<xdbob@xdbob.net\>

**Comment by OctopusET** [comment]
Okay it's fair enough, thanks everyone for the comment. tbh I think even if it's the smallest work, it's worth mentioning the author.

And I read the original PR, I think this script would be quite useful.

@markstos Could you confirm after reading new comments? If you are okay, I will just merge it.

**Comment by markstos** [comment]
I'm OK with just merging it.

**Review by OctopusET — APPROVED** [review]
Okay, LGTM

**Pull request merged**
