### PR TITLE
refactor(grimshot): modularize and clean up with functional helpers

### PR DESCRIPTION
**Pull request by Qubut**
- Introduced functional helper methods: `when`, `if_else`, and `any` for cleaner, more maintainable logic.
- Refactored conditional handling in `notifyOk`, `notifyError`, and `check` functions to leverage the new helper methods.
- Moved usage message printing to a dedicated `printUsageMsg` function.
- Extracted subject-specific logic (e.g., area, window, screen) into standalone functions: `selectArea`, `selectWindow`, etc.
- Improved error handling by introducing functions like `handleScreenshotSuccess`, `handleScreenshotFailure`, and `handleSaveCopy`.
- Reformatted code and improved readability by using consistent formatting for case statements and conditions.

This refactor enhances code maintainability by isolating logic into reusable components, improving clarity and simplifying future changes.

### CODE REVIEW

**Comment by OctopusET** [comment]
Thank you for your work, I will check it when I have some time.
I think if we are going to refactor this, we can move grimshot related files into `./grimshot` directory. Would you do that?

**Comment by Qubut** [comment]
yes it is a good idea, but I suggest that the functional_helpers file be in a folder called utils or scripts/functions or sth. like that 
since the utilities can be used in other future scripts.

**Comment by Qubut** [comment]
I've also another question, I noticed that the grim-completion script is a bash script while the grim script is a Bourne shell script
why isn't grim also a bash script ?

**Comment by OctopusET** [comment]
grimshot-completion script is added later, and someone could make zsh or fish completion script for grimshot.

**Comment by OctopusET** [comment]
I think modularization is good, but having two files won't be good for this case. Having one script file would be better to install `grimshot` script. So, I think it would be better to merge two files into one.

**Comment by Qubut** [comment]
> Thank you for your work, I will check it when I have some time. I think if we are going to refactor this, we can move grimshot related files into `./grimshot` directory. Would you do that?

I moved all related grimshot files into `./grimshot` directory as requested

also for modularity I refactored argument parsing into it's own func. and added some fixes

**Comment by Qubut** [comment]
@OctopusET Any update about this PR?

**Review by OctopusET — APPROVED** [review]
LGTM

**Comment by OctopusET** [comment]
Sorry for delay! @Qubut

**Pull request merged**
