### PR TITLE
Exception option for inactive-windows-transparency.py

### PR DESCRIPTION
**Pull request by pzant**
Adds a new option that excludes a marked window for changing transparency.
I'm not a programmer but this is tasted and works.

### CODE REVIEW

**Comment by OctopusET** [comment]
Why did you open new PR?

**Comment by pzant** [comment]
I accidentally deleted the previous repository. I'm sorry.

**Comment by OctopusET** [comment]
Okay, that's fine. I need to test this, but I can't do it right now. This might have some problems on some conditions. I will check this PR and other PRs this weekend. Thanks for your PR.

Would you make this PR into a single commit first?

**Comment by pzant** [comment]
Sorry for the chaos, can I just delete this branch and make a new commit?
Or is everything ok?

**Comment by OctopusET** [comment]
Hmm sorry, my mistake. I should've pushed new branch called `add-exception-option` to your master branch. But pushed master branch to your master.

You can pull `add-exception-option` branch from this repository and feel free to reopen it. Or I can just make it.

**Comment by OctopusET** [comment]
@pzant

**Pull request closed without merging**
