### PR TITLE
Bash completions for grimshot

### PR DESCRIPTION
**Pull request by em-s-h**

### CODE REVIEW

**Review by OctopusET — CHANGES_REQUESTED** [review]
Can you add brief instruction of this script?
Like
```
source grimshot-bash-completion.sh
```

And it would be great if you change filename like [this](https://github.com/junegunn/fzf/blob/master/shell/completion.bash)
I think `grimshot-completion.bash` would be good.

Lastly, would you squash your commits into one or meaningful chunks after you finish all your work?

**Comment by em-s-h** [comment]
Sorry for the delay, added usage instructions to the script, renamed it and squashed commits.

**Review by OctopusET — APPROVED** [review]
Delay? no. Thank you for your quick work!

LGTM

**Comment by em-s-h** [comment]
Thank you! glad to have helped.

**Pull request merged**
